### ISSUE TITLE
app.plugin is no longer a method in Diet

### ISSUE THREAD

**Issue by jaygoodfellow** [adamhalasz/diet-mysql#2]
Any plans on updating the diet-mysql module to support the latest versions of Diet?

**Comment by adamhalasz** [comment]
Hey @jaygoodfellow! Well I haven't used mysql for a while but I can do it for you when I have some more time this week. The plugin is really small so it shouldn't be too much trouble. Let me know if you have any specific suggestions :)

**Comment by adamhalasz** [comment]
Just updated the repo and gave 2 examples as well:
https://github.com/adamhalasz/diet-mysql/tree/master/examples

Let me know if you have any other questions/requests.

Cheers,
Adam
